<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Glass Bridge - SquidSphere</title>
    <link rel="stylesheet" href="game_glass_bridge.css">
</head>
<body>
    <div class="game-container">
        <!-- Game Status -->
        <div class="game-status" id="gameStatus">
            <h2>Glass Bridge</h2>
            <p id="statusText">Players crossing the bridge...</p>
            <div class="survivors-count">Survivors: <span id="survivorCount">8</span>/8</div>
        </div>
        
        <!-- Game Play Area -->
        <div class="game-play active" id="gamePlay">
            <!-- Glass Bridge -->
            <div class="bridge-container">
                <!-- Bridge Steps (18 steps) -->
                <div class="bridge-steps" id="bridgeSteps">
                    <!-- Steps will be generated by JavaScript -->
                </div>
                
                <!-- Finish Platform -->
                <div class="finish-platform">
                    <div class="finish-text">FINISH</div>
                </div>
            </div>
            
            <!-- Players Queue -->
            <div class="players-queue" id="playersQueue">
                <div class="player-item" data-player="1">
                    <img src="images/green_player.png" alt="Player 1">
                    <span class="player-number">001</span>
                </div>
                <div class="player-item" data-player="2">
                    <img src="images/green_player2.png" alt="Player 2">
                    <span class="player-number">067</span>
                </div>
                <div class="player-item" data-player="3">
                    <img src="images/green_player3.png" alt="Player 3">
                    <span class="player-number">101</span>
                </div>
                <div class="player-item" data-player="4">
                    <img src="images/green_player.png" alt="Player 4">
                    <span class="player-number">218</span>
                </div>
                <div class="player-item" data-player="5">
                    <img src="images/green_player2.png" alt="Player 5">
                    <span class="player-number">240</span>
                </div>
                <div class="player-item" data-player="6">
                    <img src="images/green_player3.png" alt="Player 6">
                    <span class="player-number">278</span>
                </div>
                <div class="player-item" data-player="7">
                    <img src="images/green_player.png" alt="Player 7">
                    <span class="player-number">324</span>
                </div>
                <div class="player-item" data-player="8">
                    <img src="images/green_player2.png" alt="Player 8">
                    <span class="player-number">456</span>
                </div>
            </div>
        </div>

        <!-- Result Screen -->
        <div class="result-screen" id="resultScreen">
            <div class="result-content">
                <h2 id="resultTitle">Bridge Crossed!</h2>
                <div class="result-stats">
                    <div class="stat-item">
                        <span class="stat-label">Survivors:</span>
                        <span class="stat-value survivors" id="survivors">-</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">Eliminated:</span>
                        <span class="stat-value eliminated" id="eliminated">-</span>
                    </div>
                </div>
                <button class="btn-back" onclick="window.location.href='games.php'">Back to Games</button>
            </div>
        </div>
    </div>

    <script src="game_glass_bridge.js"></script>
</body>
</html>
